### ISSUE TITLE
abapy in abaqus python

### ISSUE THREAD

**Issue by ahcomat** [lcharleux/abapy#1]
How to run abapy within abaqus python?

**Comment by lcharleux** [comment]
"abaqus Python" as well as "abaqus viewer -noGUI" uses your PYTHONPATH variable so if it is defined properly, you should be able to import abapy. If not, you can add the path manually using sys.path in your script.

**Comment by ahcomat** [comment]
Well I am not a professional python user. However I found a way for lazy Windows users like me. Just copy the Abapy folder to 'C:\SIMULIA\Abaqus\6.14-3\tools\SMApy\python2.7\Lib\site-packages' and it will work. Thanks for the fast reply.

**Comment by lcharleux** [comment]
It is indeed a solution because python looks at the current directory when looking for packages/modules to import. That can also be tricky if you intend to work on several projects or at least to make Abaqus work in a dedicated folder to contain the swarm of files it produces.
